name: DEV - Deploy HTML5 UP site to Cloudflare Workers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but NOT for the master branch
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          submodules: true  # (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      # deploy to cloudflare worker
      - name: Deploy
        uses: cloudflare/wrangler-action@1.2.0
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID_DEV }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'dev'
          wranglerVersion: 'latest'
